[package]
name = "gprust"
version = "0.1.0"
authors = ["scalexm <martin.alex32@hotmail.fr>"]

[dependencies]
futures = "0.1.14"
lazy_static = "0.2"

[[bin]]
name = "bin"
path = "bin/main.rs"

[lib]
name = "gprust"
path = "src/lib.rs"
