[package]
name = "gprust"
version = "0.1.0"
authors = ["scalexm <martin.alex32@hotmail.fr>"]

[dependencies]
error-chain = "0.10"
futures = "0.1.14"

[[bin]]
name = "bin"
path = "bin/main.rs"

[lib]
name = "gprust"
path = "src/lib.rs"
